# SEO settings
title: "Alex Morley"
title2: "" # default: ""
description: "Alex Morley"
keywords: "neuroscience, tech, programming, open science, open source, oss, foss"
url: https://alexmorley.me # site url
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/alexmorley/alexmorley.github.io
disqus_shortname: "alexmorley"
twitter_username: "alex__morley"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./src
destination: ./_site
keep_files: [textonly]
textbase: textonly

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Alex Morley"
  job      : "Neuroscience PhD Student"
  bio      : "Taking a break from med-school. Apparently a computer geek."
  thumb    : /images/author.jpg
  email    : alex0morley@gmail.com
  url      : https://alexmorley.me
  github   : https://github.com/alexmorley
  twitter  : https://twitter.com/alex__morley
  facebook : https://www.facebook.com/alexander.morley

# social settings
og_locale: "en_UK"
twitter_card: "summary_large_image"
twitter_site: "@alex__morley"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
